### ISSUE TITLE
Better understand timeouts

### ISSUE THREAD

**Issue by omer-shtivi** [redis-rs/redis-rs#1086]
Hello,
We are using redis in a few ways:
* redis::aio::ConnectionManager
* ConnectionPool using deadpool_redis
* redis::aio::PubSub

I have a task to add timeouts to our redis connections, as far as I understand there are three types of timeouts:
socket, command, connection

How can I set timeout for each one of the types?

**Comment by nihohit** [comment]
`deadpool_redis` isn't a part of this repo, so I can't help you with that.
I'm not well versed on this, but AFAIK socket timeout is irrelevant for async work. Please correct me if I'm wrong :).
for ConnectionManager, you'll want `Client::get_tokio_connection_manager_with_backoff_and_timeouts` in order to set timeouts.

**Comment by omer-shtivi** [comment]
Hi @nihohit ,
It is relevant, say I have the following code (pseudo):
```
let redis_client = redis::new().connect.await;
let data = redis_client.get("some_key").await.ok_or_default(|| "some value".to_string());
// do something with the data
```
if the socket hangs then the task will never continue to execute and will just await forever.

Ok, so I will wait for deadpool crate to update to redis 0.25 support, thanks
