### ISSUE TITLE
release 0.25.3 missing pub/sub methods for MultiplexedConnection 

### ISSUE THREAD

**Issue by lazareviczoran** [redis-rs/redis-rs#1137]
There seems to be a mismatch with the code present on the branch https://github.com/redis-rs/redis-rs/tree/0.25.x (the release tag has been create on a commit from this branch `Prepare release 0.25.3` [0db8ef7](https://github.com/redis-rs/redis-rs/commit/0db8ef7139a9fd04238c3970306727c672cb5506) )

and the same `Prepare release 0.25.3` commit but on the main branch [f25168d9](https://github.com/redis-rs/redis-rs/commits/f25168d938e7b6e139f54b59c0d29d01175a7501)

the pub/sub methods are missing in the release

`0.25.x` branch
https://github.com/redis-rs/redis-rs/blob/0.25.x/redis/src/aio/multiplexed_connection.rs#L477

`main` branch
https://github.com/redis-rs/redis-rs/blob/f25168d938e7b6e139f54b59c0d29d01175a7501/redis/src/aio/multiplexed_connection.rs#L565

wasn't the release supposed to be tagged of the main branch?
Is it possible to release a new version (0.25.4) with the code from `main` branch?

Thanks in advance!

**Comment by nihohit** [comment]
This isn't a mistake. Release 0.25.3 contains a bug fix that we've ported form `main`, but it doesn't contain the addition of the pubsub messages, since they're a part of a larger, breaking change, which isn't proper to release as a patch version.
These methods will be released as part of version 0.26.0, which is waiting for a couple more features to land. I don't have an ETA for when that will happen.

If it's important for you to use these methods ASAP, you can always [use the crate directly from github](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories). That will also benefit us, especially if you had feedback on the new features :)

**Comment by lazareviczoran** [comment]
Ok, thanks for clarifying :raised_hands:
