### ISSUE TITLE
Valkey support, fork, or transition

### ISSUE THREAD

**Issue by arpadav** [redis-rs/redis-rs#1138]
With the recent changes to the [Redis licensing changes](https://github.com/redis/redis/pull/13157), was wondering if there will be any accommodations for [Valkey](https://github.com/valkey-io/valkey) (fork from Linux Foundation to continue keeping the project open source)

[https://news.yahoo.com/why-aws-google-oracle-backing-163006996.html](https://news.yahoo.com/why-aws-google-oracle-backing-163006996.html)

**Comment by jaymell** [comment]
I think we're definitely interested in supporting Valkey, though not sure as of yet exactly what that's going to look like. Stay tuned!

**Comment by nihohit** [comment]
AFAIK Valkey is right now completely equivalent to the latest Redis release, and there are no plans for anything which will break the general structure of behavior - so at least the low-level `Value`-based API is very much likely to be Valkey compatible as much as it is Redis compatible.

**Comment by arpadav** [comment]
@nihohit Yea I was thinking the same thing, but I guess my original ask was a high-level inquiry about the destiny of `redis-rs` as the two projects diverge to where the differences start to have an effect. I will stay tuned, but am very interested to see how things play out. thanks though!

**Comment by gnumber13** [comment]
Can confirm atleast in my use case `valkey-server` works without issues with `redis-rs`. 

> AFAIK Valkey is right now completely equivalent to the latest Redis release, and there are no plans for anything which will break the general structure of behavior - so at least the low-level `Value`-based API is very much likely to be Valkey compatible as much as it is Redis compatible.

**Comment by jeremychone** [comment]
Just a thought, but it might be a good idea for this team to "reserve" the crate `valkey` on crates.io to secure potential future directions.

It could be confusing to have another, newer crate named `valkey` while recommending developers use `redis-rs` to communicate with the `valkey` server.

I really appreciate the high-quality code and maintenance of `redis-rs`, and hope it can become the de facto client for the `valkey` server. In fact, I would even expect the `valkey` crate to communicate with either the Redis or Valkey server, rather than the other way around.

Anyway, just a thought. Thanks for the great work! Love this crate.

**Comment by jaymell** [comment]
> Just a thought, but it might be a good idea for this team to "reserve" the crate valkey on crates.io to secure potential future directions.

@jeremychone Do you know if such a thing is possible?

**Comment by jeremychone** [comment]
@jaymell as @kamulos said, they updated their policy, but honestly, I think in this case, it really falls into genuine potential use. 
So, you would just publish an empty crate `0.0.1` and explain the context in the README.md. 

And later, if you decide not to use it, you can update it with a message "feel free to ping us if you want this crate name."

**Comment by jaymell** [comment]
I do worry about whether publishing a for-now empty crate constitutes "squatting" from crate.io's perspective, even if we do have theoretical plans to support valkey primarily in the future. I wonder if it makes sense to at least check with the valkey folks to see if they have thoughts about claiming the name. @nihohit Any thoughts?

**Comment by McFacePunch** [comment]
@jaymell 
I think this is rather urgent, I've seen some people suggesting doing this for malicious uses already and its starting to look like it could be a problem soon. I stopped by to share this little bit of threat intel since I haven't see anything done yet. Accelerating it would be in everyone's best interest.

**Comment by madolson** [comment]
@jaymell We wouldn't consider any alternative for a rust client outside of redis-rs. I would appreciate you guys squatting on the valkey crate, so I don't have any concerns about. If you would prefer I go do it, I'll go make it happen.

**Comment by jaymell** [comment]
Ok, placeholder has been pushed! Thanks everyone for bringing this up as a potential issue.

**Comment by jeremychone** [comment]
I can see it! Awesome!!!

**Comment by nihohit** [comment]
Thanks @jaymell! Can you please also update the README, so people won't be
too surprised by looking for valkeyand geting redis?

**Comment by Sir-Photch** [comment]
Just leaving my two cents here: have you also considered https://redict.io/?

**Comment by arpadav** [comment]
> Just leaving my two cents here: have you also considered https://redict.io/?

Given the industry backers of Valkey + the staleness of the current Redict repo, I'm under the personal belief that Valkey will penultimately be the de facto Redis replacement as time goes on. Not my decision, but also my two cents

**Comment by nihohit** [comment]
Closing, since hopefully https://github.com/redis-rs/redis-rs/pull/1168 is sufficient in order to handle the redis/valkey differences for the near future.

**Comment by jeremychone** [comment]
@jaymell I am revisiting this issue. I thought the `valkey` crate name was reserved by this project and had checked it after the [comment above](https://github.com/redis-rs/redis-rs/issues/1138#issuecomment-2080139643).  

However, when I check the crate now, it seems to be a completely different project: https://crates.io/crates/valkey

Am I missing something?

**Comment by nihohit** [comment]
That's interesting. Looks like somehow they got control of the crate name. Not sure how.

**Comment by jeremychone** [comment]
@nihohit Thanks for the answer. I just wanted to make sure I didn't imagine it. This is unfortunate and scary at the same time.

**Comment by jaymell** [comment]
This seems a bit shady? It's been awhile, but we did publish the crate, yes? If so, strange that any record of it has apparently been erased.

**Comment by kamulos** [comment]
would it make sense to just mail the crates.io team and ask what happened?

**Comment by zuiderkwast** [comment]
Yes, @kamulos do you want to mail the crates.io team? We in the the Valkey team are interested in this too. @madolson's comment above still stands: https://github.com/redis-rs/redis-rs/issues/1138#issuecomment-2080108537

**Comment by kamulos** [comment]
all right, sent a mail :+1: Will update once I get a response

**Comment by kamulos** [comment]
## Question

I am an active user of the redis crate. This crate is also a client for the valkey db Server. In the github discussions we noticed, that the valkey crate name, which has previously been published to by the maintainers of redis-rs suddenly changed owners.

The full discussion can be found here: https://github.com/redis-rs/redis-rs/issues/1138

The short summary is:

1. The maintainers of the valkey db server endorse the redis-rs project to be the official client
2. The maintainers of redis-rs push a placeholder to the valkey crate name
3. Everyone can see that the valkey crate is owned by the redis-rs project
4. A few months later someone notices, that valkey crate has a new owner and new code pushed to it
5. Because there is no public repository for the new code, it is difficult to try contacting the new owner directly

Can you track what happened here? If there was any rule violation can you clarify which rule this was?

## Answer

The previous owner of the valkey crate owned several reserved crates that were in violation of our new policies, so it was removed and then the name open to being taken again.

**Comment by kamulos** [comment]
So I left that uncommented, but to me this is less enlightening than hoped. I could follow up with more questions, but maybe @jaymell and @nihohit could comment if they understand.

- So the violation probably is that pushing a placeholder is not allowed? Unfortunately this is not spelled explicitly.
- What's the deal with "several reserved crates"? Were multiple crates removed?
- If the current crate complies with the rules, this is really unfortunate. Because it would have been easy to push something like that back then... :shrug:
