### ISSUE TITLE
Multiplexed connection with backoff?

### ISSUE THREAD

**Issue by omer-shtivi** [redis-rs/redis-rs#1148]
Hello,
For the ConnectionManager there is an api `get_tokio_connection_manager_with_backoff_and_timeouts` but to get multiplexed connection there is only `get_multiplexed_async_connection_with_timeouts` is it intentional that there is no backoff?

**Comment by nihohit** [comment]
What would backoff mean in the case of a multiplexed connection?

**Comment by omer-shtivi** [comment]
Consumer: trying to connect and consume messages, fails to connect -> backoff
Producer: try to produce a message, fails to connect -> backoff?

**Comment by nihohit** [comment]
I'm not sure what does either a producer or a consumer means in this context, since a multiplexed connection is neither, but a reconnect-with-backoff logic can be easily implemented by the user. If the user wants this mechanism from the library, they can use the connection manager. What's the scenario in which a backoff-and-reconnect mechanism is needed, that the connection manager isn't good for?

**Comment by omer-shtivi** [comment]
Sorry, I had the PubSub in mind.
I will close the issue, thanks

**Comment by nihohit** [comment]
If you're looking for the RESP3 pubsub, you can use both the multiplexed
connection and the connection manager - just note that you'll need to
manually reconnect after disconnects.

**Comment by nihohit** [comment]
I missed the fact that the connection manager has no pubsub methods 🤦 
https://github.com/redis-rs/redis-rs/pull/1149 should fix this.
