### ISSUE TITLE
TypeError: "Response type not convertible to numeric"

### ISSUE THREAD

**Issue by omer-shtivi** [redis-rs/redis-rs#1151]
Hello,
We tried to upgrade from version 0.21 to version 0.25.3.
After the upgrade we got the following error:
```
TypeError: "Response type not convertible to numeric"
```
When checking the key it is nil:
```
redis-cli get <PATH_TO_KEY>/test.public.employees
(nil)
```
Here is the call which causes the issue:
```
  redis::pipe()
      .atomic()
      .set(&redis_path, data)
      .expire(&redis_path, redis_ttl_sec)
      .ignore()
      .get(&redis_path)
      .query_async(&mut conn_manger)
      .await?
```

Any idea why this error happens? or how can we further debug it?

**Comment by nihohit** [comment]
Convert the response to string or redis::Value, and see what was the
response.

**Comment by omer-shtivi** [comment]
Tried to do:
```
                    let results: String = redis::pipe()
                        .atomic()
                        .set(&redis_path, data.clone())
                        .ignore()
                        .expire(&redis_path, redis_ttl_sec)
                        .ignore()
                        .get(&redis_path)
                        .query_async(&mut conn_manger)
                        .await?;
                    tracing::info!("results: {}", blabla);
```
with no luck (both trying to convert to String, and add the ignore to the set), same error

**Comment by omer-shtivi** [comment]
Also tried to change to Option<String> with no luck

**Comment by nihohit** [comment]
Have you tried using redis::Value?

**Comment by omer-shtivi** [comment]
Yes, just tried, it out, this is what we get:
```
bulk(binary-data([161, 100, 116, 97, 103, 115, 162, 163, 101, 112, 97, 114, 116, 115, 129, 101, 101, 109, 97, 105, 108, 109, 115, 101, 109, 105, 95, 108, 111, 99, 97, 116, 105, 111, 110, 246, 112, 101, 110, 99, 111, 100, 101, 100, 95, 108, 111, 99, 97, 116, 105, 111, 110, 102, 101, 109, 97, 105, 108, 46, 161, 101, 69, 77, 65, 73, 76, 162, 109, 99, 108, 97, 115, 115, 105, 102, 105, 101, 114, 95, 105, 100, 162, 109, 99, 108, 97, 115, 115, 105, 102, 105, 101, 114, 95, 105, 100, 101, 69, 77, 65, 73, 76, 103, 118, 101, 114, 115, 105, 111, 110, 0, 109, 108, 101, 97, 114, 110, 101, 100, 95, 101, 112, 111, 99, 104, 27, 0, 0, 1, 142, 241, 71, 58, 150, 163, 101, 112, 97, 114, 116, 115, 129, 107, 101, 109, 112, 108, 111, 121, 101, 101, 95, 105, 100, 109, 115, 101, 109, 105, 95, 108, 111, 99, 97, 116, 105, 111, 110, 246, 112, 101, 110, 99, 111, 100, 101, 100, 95, 108, 111, 99, 97, 116, 105, 111, 110, 108, 101, 109, 112, 108, 111, 121, 101, 101, 95, 105, 100, 46, 161, 106, 69, 77, 80, 76, 79, 89, 69, 69, 73, 68, 162, 109, 99, 108, 97, 115, 115, 105, 102, 105, 101, 114, 95, 105, 100, 162, 109, 99, 108, 97, 115, 115, 105, 102, 105, 101, 114, 95, 105, 100, 106, 69, 77, 80, 76, 79, 89, 69, 69, 73, 68, 103, 118, 101, 114, 115, 105, 111, 110, 0, 109, 108, 101, 97, 114, 110, 101, 100, 95, 101, 112, 111, 99, 104, 27, 0, 0, 1, 142, 241, 71, 58, 150]))
```
and we try to covert to:
```
Option<Vec<u8>>
```

**Comment by nihohit** [comment]
That's because you have an array of values, where the first result is an
array of bytes - the binary data. Those are nested arrays. When you ask it
to convert to Vec<u8>, the function probably expands the external array to
the vec, and then tries to convert the internal array to a u8, hence the
numeric error.
I'm not sure when did this degradation happen, or whether it actually is a
degradation - can't say I like this implicit flattenning
I don't know when will i have the availability to look into this, so for
now you can try converting to (Vec<u8>), or to Vec<Vec<u8>>, and assume
there's only one item in the external array.

**Comment by omer-shtivi** [comment]
we tried to a `vec<vec<u8>>` and got: 
```
RedisError(\"Response was of incompatible type - TypeError: \\\"Response type not vector compatible.\\\" (response was ok)\")
```

**Comment by nihohit** [comment]
Was that before you ignored the set operation?

**Comment by omer-shtivi** [comment]
It worked, thanks, I removed the ignore at the second try

**Comment by nihohit** [comment]
Now that I'm next to a computer, I can add for the record:
This was broken by commit https://github.com/redis-rs/redis-rs/commit/850f5f90e98b45b698d6fb8ee4bc41551660ea31 . IMO the implicit flattening isn't something positive - in this example it allowed the user to miss the fact that the results that they return are always incorrect - in my tests, even in the version where this ran without an error the result was always an empty Vec, because when trying to convert `Vec<Value>` to `Vec<u8>`, since no value was convertible to `u8` (assuming the `set` operation set the value shown here https://github.com/redis-rs/redis-rs/issues/1151#issuecomment-2063861669). The former implementation silently failed consistently, the currently implementation conveys the failure to the user.

**Comment by GopherJ** [comment]
I'm getting again this error:

"Response type not convertible to numeric." (response was bulk(string-data('"0"')))

**Comment by nihohit** [comment]
Right, this is correct. It's an array of strings of numbers, not a single
number.

**Comment by GopherJ** [comment]
@nihohit but when I store it I stored it as a u64

**Comment by nihohit** [comment]
Can you post your get & set code?
