### ISSUE TITLE
Allowing the requirement of a tcp timeout when using sentinel as well as when using redis client directly

### ISSUE THREAD

**Issue by jrylander** [redis-rs/redis-rs#1162]
The sentinel client is using get_multiplexed_async_connection which uses long timeout. It would be useful for us to have the connection timeouts being configurable when using redis via sentinels as well as when accessing a redis server directly.

Do you think is it feasible to have timeout as an option in the sentinel client and use that when creating connections?

**Comment by nihohit** [comment]
I don't think any of the maintainers has time to implement this right now,
but this should be pretty easy to implement if you want to contribute it.
Just please be aware of
https://github.com/redis-rs/redis-rs/issues/1147#issuecomment-2047893934 -
that is, don't add a '_with_timeouts' function, like we've used in the
past, but add a '_with_config' function, so that we won't have an explosion
of options and matching functions.

**Comment by jrylander** [comment]
I will give it a go

**Comment by jrylander** [comment]
I put together https://github.com/redis-rs/redis-rs/pull/1167

I am not sure my code is up to snuff for this project though but hope it is useful.

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/1167
