### ISSUE TITLE
Warning about Rust 2024 with the newest Nightly Compiler: `this function depends on never type fallback being ()`

### ISSUE THREAD

**Issue by kamulos** [redis-rs/redis-rs#1228]
In my code I often use code that ignores the return value of operations like `set`:

```rust
use redis::{Commands, Connection, RedisError};

fn do_something(connection: &mut Connection) -> Result<(), RedisError> {
    connection.set("test", "test_data")?;
    Ok(())
}
```

Now with the newest nightly compiler I get the following warning:

```
warning: this function depends on never type fallback being `()`
 --> src/main.rs:3:1
  |
3 | pub fn do_something(connection: &mut Connection) -> Result<(), RedisError> {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #123748 <https://github.com/rust-lang/rust/issues/123748>
  = help: specify the types explicitly
note: in edition 2024, the requirement `!: FromRedisValue` will fail
 --> src/main.rs:4:16
  |
4 |     connection.set("test", "test_data")?;
  |                ^^^
  = note: `#[warn(dependency_on_unit_never_type_fallback)]` on by default
```

Now I don't entirely understand what's going on here, but this warning seems to be fixable for me like this:

```diff
- connection.set("test", "test_data")?;
+ let _: () = connection.set("test", "test_data")?;
```

This is just not very convenient nor pretty. Am I doing something wrong? Is there any way the `redis` crate can mute this warning?

**Comment by nihohit** [comment]
I'm looking into this, but ATM I'm not sure how to solve this on the crate side.

**Comment by kamulos** [comment]
Hmm, just tried it again. I think this could basically be the following situation:

```rust
#![feature(never_type)]

trait Constructible {
    fn construct() -> Self;
}

impl Constructible for () {
    fn construct() -> Self {
        ()
    }
}

// impl Constructible for ! {
//     fn construct() -> Self {
//         loop {}
//     }
// }

fn generic_return<T: Constructible>() -> Result<T, ()> {
    Ok(T::construct())
}

fn main() -> Result<(), ()> {
    generic_return()?;
    Ok(())
}
```

If I enable the implementation for `!`, the warning goes away. Unfortunately I still don't understand it...

**Comment by nihohit** [comment]
> Unfortunately I still don't understand it...

https://discord.com/channels/273534239310479360/1253055949598363760

join the club 😅

**Comment by kamulos** [comment]
I don't think I have access via your link. Do I need to join a specific channel before I can read that?

What I also noticed in my example is as soon as I replace the `?` by `.unwrap()` it stops working entirely without an explicit specification of the generic return type.

```rust
fn main() -> Result<(), ()> {
    generic_return().unwrap();
    Ok(())
}
```

To me it feels like these two should be interchangeable without such different type inference.

**Comment by nihohit** [comment]
> I don't think I have access via your link

You need to join the Rust Programming Language server - https://discord.com/invite/rust-lang-community 

> To me it feels like these two should be interchangeable without such different type inference.

No, because ? desugars to a match, see https://github.com/rust-lang/rust/issues/51125#issuecomment-1991733203/

**Comment by nihohit** [comment]
@kamulos https://github.com/redis-rs/redis-rs/pull/1229 exposes the `exec/_async` functions that mitigate this, but don't solve the issue for higher level functions.

**Comment by kamulos** [comment]
Thanks a lot for working on this!

I am still wondering what the long-term view on this is. Maybe at some point the solution will be to just say: `impl FromRedisValue for !`... that seems to work for my example and should bring back the current behavior.

Somehow I feel like it would be a nice addition to the Rust language to make the behavior for these kinds of type inference (where there is no return type) customizable. But I am sure this would get complicated pretty fast.

**Comment by julianskartor** [comment]
Hi there! I just stumbled upon this issue as well. In the [tracking issue](https://github.com/rust-lang/rust/issues/123748) the rust team mention:

> However, this can also be a sign that you don't care what the type is, and maybe the better solution is to refactor the code.

Is there an understanding whether this would be possible in redis-rs or not? If not, is it a sign that this language feature is not quite yet ready for stabilization? I wonder if it's worth flagging this to the rust team :thinking:

**Comment by nihohit** [comment]
> whether this would be possible in redis-rs or not

AFAIK this isn't possible without breaking backward compatibility. AFAIS, any function where the user may or not care about the result has to be written with a generic return type and the user has to explicitly opt-out of the type.

>  is it a sign that this language feature is not quite yet ready for stabilization?

🤷

**Comment by traviscross** [comment]
> I don't think I have access via your link. Do I need to join a specific channel before I can read that?
> 
> What I also noticed in my example is as soon as I replace the `?` by `.unwrap()` it stops working entirely without an explicit specification of the generic return type.
> 
> ```rust
> fn main() -> Result<(), ()> {
>     generic_return().unwrap();
>     Ok(())
> }
> ```
> 
> To me it feels like these two should be interchangeable without such different type inference.

This is due to the issue described here:

https://github.com/rust-lang/rust/pull/122412

**Comment by traviscross** [comment]
> ...but this warning seems to be fixable for me like this:
> 
> ```diff
> - connection.set("test", "test_data")?;
> + let _: () = connection.set("test", "test_data")?;
> ```

You could shorten that a bit to:

```diff
- connection.set("test", "test_data")?;
+ () = connection.set("test", "test_data")?;
```

**Comment by traviscross** [comment]
Here's a self-contained minimization of what is happening:

```rust
#![deny(dependency_on_unit_never_type_fallback)]

pub trait ToRedisArgs {}
pub trait FromRedisValue {}
pub type RedisResult<T> = Result<T, ()>;

impl ToRedisArgs for () {}
impl FromRedisValue for () {}

pub struct Connection;
impl Connection {
    pub fn set<
        'a,
        K: ToRedisArgs,
        V: ToRedisArgs,
        RV: FromRedisValue,
    >(
        &mut self,
        _: K,
        _: V,
    ) -> RedisResult<RV> {
        todo!()
    }
}

pub fn test(conn: &mut Connection) -> Result<(), ()> {
    //~^ ERROR this function depends on never type fallback being `()`
    conn.set((), ())?;
    //~^ ~~~
    //~| NOTE in edition 2024, the requirement `!: FromRedisValue` will fail
    Ok(())
}

fn main() {}
```

As was pointed out above, if we replace `?` with `.unwrap()` we'll get type `ERROR type annotations needed` because the generic parameter in the return value of `set` (`RV`) is entirely unconstrained.  The only reason it works with `?` is because of how the desugaring of `?` skews inference.

The specific reason that it's warning here is because that `RV: FromRedisValue`.  The bound means that, for this code to be valid, the type inferred must implement `FromRedisValue`.  In `redis-rs`, there is an `impl FromRedisValue for ()`, but there's not an `impl FromRedisValue for !`.  Since the fallback type is going to change from `()` to `!` in Rust 2024 (and, we hope, in all editions later), this code will break, since `!` will be inferred instead of `()`, and that will not implement `FromRedisValue`.

**The direct way to fix this is as follows.**  Since `!` isn't stable, we can't write that missing impl directly, but we can using the "never type hack":

```rust
#![deny(dependency_on_unit_never_type_fallback)]

#[doc(hidden)]
pub trait NeverTypeHack {
    type Output;
}
impl<T> NeverTypeHack for fn() -> T {
    type Output = T;
}
pub type Never = <fn() -> ! as NeverTypeHack>::Output;

pub trait ToRedisArgs {}
pub trait FromRedisValue {}
pub type RedisResult<T> = Result<T, ()>;

impl ToRedisArgs for () {}
impl FromRedisValue for () {}
impl FromRedisValue for Never {}

pub struct Connection;
impl Connection {
    pub fn set<
        'a,
        K: ToRedisArgs,
        V: ToRedisArgs,
        RV: FromRedisValue,
    >(
        &mut self,
        _: K,
        _: V,
    ) -> RedisResult<RV> {
        todo!()
    }
}

pub fn test(conn: &mut Connection) -> Result<(), ()> {
    conn.set((), ())?;
    Ok(())
}

fn main() {}
```

We generally discourage the never type hack, and we've never promised this will continue to work, as we consider it a bit of an accidental stabilization, but our current plans don't involve breaking it, and it does do want you may want here.

However, the effects of a generic parameter like this one that's not constrained by any input argument is probably always going to be surprising due to quirks of type inference like never type fallback and the inference-skewing behavior of `?`, so if this design can't be avoided, I'd recommend at least that the document should loudly advise people to *always* constrain the return type of these functions, either directly, or by using turbofish to give a type argument for the `RV` parameter.

**Comment by nihohit** [comment]
@traviscross Thanks for the thorough explanation! 
If you have the time I'd appreciate an explanation of the process here - I assume that the issue of functions with side effects with genric return types which can be ignored is rather common, and that other crates experienced this issue. IS this something you find in a crater run? and how was it taken into account when considering this fix?

**Comment by traviscross** [comment]
It's probably less common than you would expect for the reason I mentioned, which is that this kind of pattern is fated to have subtle and surprising behavior in Rust.  Note that the key here is not just that the return type is generic (that's fine) but that it's also 1) unconstrained by any input parameter and 2) expected to be unused.

We did a crater run [here](https://github.com/rust-lang/rust/pull/123482).  The fallback change breaks something on the order of 0.4% of crates that we check[^1].  This also includes breakage due to other patterns than the one here.

[^1]: The denominator on this crater run looks artificially lower because we had already filtered out hundreds of thousands of crates in an earlier run that would not break.

That's non-zero, but that is acceptable over an edition, and the upside of this is high, as this will hopefully allow us to later stabilize the never (`!`) type.

As a mitigation, we implemented a number of lints that will warn people about this far ahead of time.  E.g., this lint:

- https://github.com/rust-lang/rust/pull/125289

...is the one that provides the warning against what's happening here, and this will land in Rust 1.81 (which will be released 2024-09-05), and consequently, users on stable Rust will start seeing warnings related to the pattern described in this issue unless those users constrain the return type.

**Comment by nihohit** [comment]
Thank you!

**Comment by WaffleLapkin** [comment]
I also want to notice that implementing `FromRedisValue` for `!` is **not** what you want. It will lead to the code example in question breaking at runtime, rather than compile time, since `!` cannot be constructed.

The solution is to explain to users that they need to constrain the return type (just as they already need with the `.unwrap()`) and/or add functions which always return `Result<(), _>`, rather than a generic return.

> Note that the key here is not just that the return type is generic (that's fine) but that it's also 1) unconstrained by any input parameter and 2) expected to be unused.

And 3) it has to be a `Result<Generic, _>` or `Option<Generic>` specifically.

**Comment by nihohit** [comment]
@kamulos can this issue be closed?

**Comment by kamulos** [comment]
Yes, thanks everyone for the explanations

**Comment by MurrayGroves** [comment]
Has there been any more discussion about updating the macros? Stumbled across this discussion because it's frustrating to either have a bunch of warnings in my project or extra unit types i.e.`() = con.rpush(bla bla)`. I don't understand the talk about specific types for whether the caller cares about the return value or not. Why can't each macro return a suitable type, e.g. `rpush` returns some uint, and then the caller can simply choose not to do anything with the value.

**Comment by nihohit** [comment]
> Why can't each macro return a suitable type, e.g. rpush returns some uint

Because that would break existing code, since users can choose to parse it as a string instead of uint.
A possible solution is to create a V2 set of macros, imported separately, with concrete expected types instead of allowing the users to define the target type, but I have other fish to fry ATM. If you want to contribute that, it would be appreciated.
