### ISSUE TITLE
Is pooling `ConnectionManager` unnecessary?

### ISSUE THREAD

**Issue by feelingsonice** [redis-rs/redis-rs#1319]
Redis [recommends](https://redis.io/kb/doc/2c9kbsv6bi/should-connection-pooling-be-used) always pooling the connection. It says that:

>"Otherwise, each request will open a new connection." 

I don't see the `redis-rs` implementation doing this, and the `ConnectionManager` seems perfectly fine as a standalone. So my question is, is it unnecessary to wrap `ConnectionManager` around something like [`deadpool`](https://github.com/bikeshedder/deadpool)? Especially since `ConnectionManager` already manages the connection and its clonable?

**Comment by jaymell** [comment]
There are definitely use cases for pooling, e.g., if you're making blocking calls like `BLPOP`, which will otherwise block concurrent requests on the underlying `MultiplexedConnection`. Otherwise, a single `ConnectionManager` should be sufficient and preferred -- using a different connection for each request is potentially much more resource intensive. 

To be clear, though, don't try to pool `ConnectionManager`s. Rather, use crates like deadpool and bb8, which already have "Manager" types to handle pooling of `MultiplexedConnection`s for you.

**Comment by feelingsonice** [comment]
>using a different connection for each request is potentially much more resource intensive.

For just basic operations like `GET`, is there ever a point where it'd be beneficial to create a pool of _shared_ connections? I have around few thousand `get` calls a second. Because `deadpool` blocks concurrent requests on the same connection, I was thinking of just manually creating a slice of N different `ConnectionManager`, round robin or get a random one and clone it for each request. Do you think that's unnecessary?

**Comment by jaymell** [comment]
> I was thinking of just manually creating a slice of N different ConnectionManager, round robin or get a random one and clone it for each request. Do you think that's unnecessary? I'm guessing the multiplexed connection is enough?

What is your goal in doing this? There should be no performance benefit here. If you're concerned about connections failing for some unknown/unrecoverable reason and want to have a fallback, that's understandable, but I don't think there's any benefit to doing so, short of a bug in the library or a failure case that hasn't been covered. If there are any pooling libraries that can just clone connections rather than lock them with a Mutex, that may meet your needs. I have no idea whether any of the pooling libs out there currently do this.  

> A single ConnectionManager can easily handle O(1k) GET requests per second. I'd start with it, and use more complex structures only if you see a need for it.

My company uses this setup in production, i.e., a single `ConnectionManager` per application instance, and has had no issues.
