### ISSUE TITLE
Corrupt connections

### ISSUE THREAD

**Issue by importcjj** [redis-rs/redis-rs#325]
Is it possible to have a such situation on an asynchronous connection?

1. `PING` query sent a `PING` to the server via a certain connection, and the server returned a `PONG` response.
2. Before reading the response,  an error (timeout, etc) occurred, and the query was interrupted, but the connection was still alive.
3. The next `GET` query sent some bytes and used the `PONG` remained above as a response from the server.

Or maybe you can look at those:

https://github.com/importcjj/mobc/issues/28
https://github.com/importcjj/mobc/issues/29

**Comment by Marwes** [comment]
I can see how that would happen with `aio::Connection`. If the query_async call is interrupted before it can read the response then the next call must completely read any interrupted request before proceeding.

**Comment by importcjj** [comment]
What about adding a new `req_failed` flag to every async connection. when an error occurs in the ` req_packed_command` function(either fail to write or read), this flag will be set to `True`, and then users can know the prev req of this connection was failed.

**Comment by importcjj** [comment]
@Marwes for a connection pool, this flag is important for it to determine if a connection should be dropped when check-in.

**Comment by tailhook** [comment]
> What about adding a new `req_failed` flag to every async connection. when an error occurs in the ` req_packed_command` function(either fail to write or read), this flag will be set to `True`, and then users can know the prev req of this connection was failed.

Better approach would be a flag `in_progress` which is raised when starting request and is cleared after response is fully received. Then in progress connections should be dropped when reach a connection pool (because future that is able to finish the request correctly is dropped).

**Comment by Marwes** [comment]
This isn't because of an error though, the problem is that a timeout interrupts the connection in the middle of reading or writing  on the socket which leaves the connection in an undeterminate state.

I can see two solutions here

* Mark the connection as `request_started` before every read/write and clear the flag after the response has been fully read. If another request starts and it finds that `request_started == true` it knows that there is a request that never finished completely and there is no way to recover, just return an error. 
This is easy to implement but makes `Connection` pretty bad to work with if timeouts are used as timeouts will almost always mean that the connection is unrecoverable and a full reconnect is needed.

* Store all the state needed to continue executing a previous request inside `Connection` itself (not in the future). This includes how many bytes were written so far in a request etc so that an earlier, interrupted request can be fully sent and the response received before the next request is sent.
A bit tricker since we can't even use helpers like `write_all` but it would probably be more user friendly.

**Comment by tailhook** [comment]
>     * Store all the state needed to continue executing a previous request inside `Connection` itself (not in the future). This includes how many bytes were written so far in a request etc so that an earlier, interrupted request can be fully sent and the response received before the next request is sent.
>       A bit tricker since we can't even use helpers like `write_all` but it would probably be more user friendly.

This is not only a problem of complexity, but also poses another problem: if previous request times out, it probably means that something wrong with this TCP connection or too much data is returned. So waiting in the next request may slow down the application. It's safer to drop connection and reconnect.

**Comment by silence-coding** [comment]
No one fixes it?

**Comment by Marwes** [comment]
I'd be happy to take a PR to fix this. The `MultipledConnection` does not have this issue however and is much more flexible. I don't use the simple async `Connection` myself so what little time I have I do have to work on redis-rs, I have to spend that elsewhere.

**Comment by Marwes** [comment]
Here is a test that should pass if the connection is able to cope with a query being dropped. Though just consistently returning an error instead would also be ok.

```rust
#[test]
fn drop_safe() {
    let ctx = TestContext::new();

    block_on_all(async move {
        let mut conn = ctx.async_connection().await?;
        cmd("PING")
            .arg("wrong")
            .query_async::<_, String>(&mut conn)
            .now_or_never();

        let value: String = cmd("PING").arg("right").query_async(&mut conn).await?;

        assert_eq!(value, "right");

        Ok::<_, RedisError>(())
    })
    .unwrap();
}

```

**Comment by kvcache** [comment]
Looks like this is a known issue. Here's my repro from today:
```rust
use redis::AsyncCommands;

#[tokio::main]
async fn main() {
    let client = redis::Client::open("redis://localhost:6379").unwrap();

    let mut handle = client.get_async_connection().await.expect("reason");

    {
        let _: () = handle.set("key", "this is not a pong").await.expect("reason");
        let future = Box::pin(
            handle.get::<&str, String>("key")
        );
        // Move the request 1 state forward
        let _poll_result = futures::poll!(future);
        // Drop the request Future, like a web request Future cancellation will do.
        // Connection pools like bb8 also reuse this connection handle; this is just
        // a minimal demonstration of the issue
    }

    let pong: String = redis::cmd("PING").query_async(&mut handle).await.expect("reason");
    println!("\nping?\n redis says: {pong:?}\n")
}
```

which prints:
```
ping?
 redis says: "this is not a pong"
```

In case you want to run, here's what I used:
```toml
[dependencies]
tokio = { version = "1.19", features = ["full"] }
redis = { version = "0.22", features = ["tokio-comp"] }
futures = { version = "0.3" }
```

This makes it kind of impossible to use Redis in a tonic grpc server, on account of deadlines and Future cancellations. It would be fine if it just error'd on the 2nd use.
Actually the best/easiest thing I can think of would be to expose something on `redis::aio::Connection` such that `bb8::ManageConnection::has_broken` could drop these who-knows-what-state handles

**Comment by tdyas** [comment]
> Actually the best/easiest thing I can think of would be to expose something on redis::aio::Connection such that bb8::ManageConnection::has_broken could drop these who-knows-what-state handles

At my last employer, I wrote an async client on type of the `redis` crate which serialized requests into a `bytes::Bytes` and then sent them on a channel (from `async-channel` crate) to several tokio tasks (spawned with `tokio::spawn`) which then actually sent the requests using the `redis` crate. A one shot channel then sent the result back to the part of the program that generated the Redis request. This side stepped the issue with connection drops since the tasks each managed an individual Redis connection and would not be dropped if the other end of the channel used to receive requests was dropped.

**Comment by kvcache** [comment]
@tdyas Thanks for the idea! I am hoping to keep this as light as possible but I will keep it in mind. I already have my own ConnectionManager and might end up wrapping ConnectionLike... Maybe you'd like to opine on the PR I opened for this?

**Comment by nihohit** [comment]
As mentioned, `MultiplexedConnection` is the type to use instead of `aio::Connection`.

**Comment by Cheban1996** [comment]
@nihohit Yeah.. it resolve my truble
Thank you so much
