### ISSUE TITLE
Add support for pyo3 and conversion to PyErr

### ISSUE THREAD

**Issue by TheButlah** [redis-rs/redis-rs#375]
Would it be possible to add better pyo3 support by implementing conversion to/from `PyErr` and `RedisError`? There are probably other types/traits to support as well.

**Comment by weihanglo** [comment]
I think this kind of conversions should be handled by application developers. Here are my two cents: 

redis-rs is a general-purpose Rust lib for Rust target. Not a crate targeting for Python-binding. It's weird to implement  conversions for downstream clients in a upstream library. If we implement`impl From<RedisError> for PyErr` today, maybe next week we need `impl From<RedisError> for JsError`, and so on and so forth. The maintenance cost go skyrocketing and become overwhelming. And a redis-rs maintainer might be a Redis expert but not a Python/Node.js/Ruby veteran so they has chance to make mistakes on Error <-> `pyo3::exceptions` implementations.

As a redis-rs + pyo3 user, due to the orphan rule, unfortunately one of the solutions is to create a wrapper type on `RedisError`. Or just use a generic type such as`Box<Result>`, but this solution looks weird and not fit in pyo3 case . Luckily, we are in the age where [thiserror](https://github.com/dtolnay/thiserror) and other great error handling crates exist! No more boilerplates (or just a little) with these awesome stuff. 😀

<details>
<summary>Expand this simple snippet about type-wrapping if you need.</summary>

```rust
use pyo3::prelude::*;
use pyo3::wrap_pyfunction;
use pyo3::exceptions::ConnectionError;

#[pyfunction]
fn connect() -> PyResult<()> {
    redis_connect()?;
    Ok(())
}

fn redis_connect() -> Result<(), MyRedisError> {
    let _ = redis::Client::open("redis://127.0.0.1")?.get_connection()?;
    Ok(())
}

struct MyRedisError(redis::RedisError);

impl From<redis::RedisError> for MyRedisError {
    fn from(error: redis::RedisError) -> Self {
        Self(error)
    }
}

impl From<MyRedisError> for PyErr {
    fn from(error: MyRedisError) -> Self {
        ConnectionError::py_err(error.0.to_string())
    }
}

#[pymodule]
fn redis_rs(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_pyfunction!(connect))?;
    Ok(())
}
```

</details>

**Comment by TheButlah** [comment]
@weihanglo Yes, my concern is exactly that - the orphan rule causes downstream developers to have to wrap types, whereas this effort would not need to be duplicated if it was feature gated in redis-rs. 

I'm fairly new to rust, so I'm not familiar with the typical way of dealing with the orphan rule. In my code, I am doing basically just what you listed above. Is there a better way to do it? If not, and if its just the above boilerplate, why not accept a PR adding it via a feature gate? Yes this would be a combinatorial explosion, but thats only assuming people actually care enough to submit PRs :P

**Comment by weihanglo** [comment]
> Yes this would be a combinatorial explosion, but thats only assuming people actually care enough to submit PRs :P

Fair point. But as I aforementioned, this assumes redis-rs maintainers must also have knowledge about Python (mitsuhiko definitely has a lot 😆) or other downstream libraries. IMO maintainers should only accept PRs which they are capable to maintain. whenever a related issue happens, they must fix themselves instead of expecting the original PR author would come and conquer. The lifetime of code in a PR must live longer than the PR itself 😜

The thorny orphan rule problem can be dealt in both side. Given the conversion code is more close to downstream one than Redis itself. Maybe put them in pyo3 or something like pyo3-contrib is a reasonable choice. Other similar issues can follow this solution and gain benefits and supports from pyo3 community. Would this be a case?

**Comment by TheButlah** [comment]
I found this advice from https://github.com/Ixrec/rust-orphan-rules:
>If the trait's crate is "clearly more fundamental" than the type's crate, or vice versa, then the "less fundamental" crate is probably the best home for that impl. For example, if I write a linear-algebra crate with Matrix and Vector types, I should probably provide impls for num-traits like MulAdd and Pow.

I interpret this as meaning that the `redis-rs` repo rather than the `pyo3` repo should provide the impls. The notion of adding it to a `pyo3-contrib` crate is a good idea, but unfortunately I don't think such a repo exists.

For now, if it won't be accepted due to maintenence concerns, then I suppose theres nothing that can be done about that. I'll close the issue. Thanks anyway!

**Comment by weihanglo** [comment]
The `num-traits` example indicates that we should definitely not provide `impl From<RedisEror> for PyErr` in std. However, it still does not answer which type crates is the best home for that. 

I admit it would be easier to put impl in redis-rs, and as I am not a maintainer of redis-rs nor have privileges to decide where to go, @TheButlah you can reopen the issue and discuss with others as you wish :)

**Comment by nihohit** [comment]
closing - this will not be accepted, due to maintenance concerns.
