### ISSUE TITLE
Support for mTLS

### ISSUE THREAD

**Issue by GrandChaman** [redis-rs/redis-rs#393]
It would be nice to be able to connect to `redis` using a TLS client certificate and key.
The connection setting would need to allow the following :
- Client certificate
- Client key
- CA Certificate (in case of self-signed)

**Comment by npajkovsky** [comment]
Yah, I'm looking for this feature as well.

**Comment by npajkovsky** [comment]
I wanted to add support for mTLS from `redis-rs`, but it truns out, it not an easy task at all.
The bit of stats: last year, project received 234 non-merged commits[1] from 48 individual contributors. That's not many,
if you consider number of features Cargo.toml has.

With that in mind, I have couple questions:

1. Do we need two async runtimes? Would be just fine have only tokio for now?
2. Do we need `connection-manager` feature? Would be just fine use `r2d2`, `bb8` or `deadpool`?

If nothing can be dropped, adding mTLS become nightmare, because `native-tls` supports only
`Identity`, pfx format for CA, priv and cert. That's not what is used in production much.

`native-tls` must be swapped with `rustls` or `openssl` and have to implemented for tokio and async.

@Marwes @mitsuhiko What do you think?

[1]: git log --no-merges --since='1 years ago' --format='%an <%ae>' | sort | uniq -c | sort -k1 -n -r | awk 'BEGIN {FS = "|"} ; {sum+=$1} END {print sum}'

**Comment by Marwes** [comment]
> Do we need two async runtimes? Would be just fine have only tokio for now?

Personally I only care about tokio, but I know others want the async_std runtime so I don't think removing it is an option.

> Do we need connection-manager feature? Would be just fine use r2d2, bb8 or deadpool?

Not sure how that would help? I'd expect that (and most features) to be orthogonal to adding additional TLS options. The only thing I see complicating that is if it were to be added for multiple runtimes but if you only need the support in one then just implement it for that runtime.

More broadly, I believe we should expose a way to inject any type implementing `AsyncRead + AsyncWrite` instead of being hardcoded to TCP/UNIX/TCP+TLS . That should let users customize things like TLS however they want before constructing a redis connection.

**Comment by npajkovsky** [comment]
> > Do we need two async runtimes? Would be just fine have only tokio for now?
> 
> Personally I only care about tokio, but I know others want the async_std runtime so I don't think removing it is an option.
> 
> > Do we need connection-manager feature? Would be just fine use r2d2, bb8 or deadpool?
> 
> Not sure how that would help?

It would just reduce line of codes, close some issues and be super-seeded by creates, designed to do connection management. 

> I'd expect that (and most features) to be orthogonal to adding additional TLS options. The only thing I see complicating >that is if it were to be added for multiple runtimes but if you only need the support in one then just implement it for that
> runtime.

Yes, true.

> More broadly, I believe we should expose a way to inject any type implementing `AsyncRead + AsyncWrite` instead of being hardcoded to TCP/UNIX/TCP+TLS . That should let users customize things like TLS however they want before constructing a redis connection. I have moved the code towards this capability but I haven't gotten there yet.

Do you have somewhere branch/git/tag?

**Comment by Marwes** [comment]
It is merged a couple of months ago as a refactoring of other stuff. Nothing specific, just moving things closer to being able to accept a `AsyncRead + AsyncWrite` argument.

**Comment by Marwes** [comment]
https://github.com/mitsuhiko/redis-rs/pull/438 lets you construct a connection object by passing it an arbitrary stream which lets you initialize, for example, a TLS stream and the construct the connection with it which should solve this issue.

**Comment by nonirosenfeldredis** [comment]
Hi ! I created this PR [support MTLS](https://github.com/redis-rs/redis-rs/pull/791). 
waiting for review and approval .

**Comment by nihohit** [comment]
implemented in https://github.com/redis-rs/redis-rs/pull/858
