### ISSUE TITLE
0.22.0 release planning

### ISSUE THREAD

**Issue by djc** [redis-rs/redis-rs#672]
Just a placeholder for now, there's probably more stuff we'll want to land.

**Comment by rudolphfroger-ds** [comment]
Hi Dirkjan, it's nice to see you picking up development for this crate!

With regards to releasing, maybe you can also update the CHANGELOG for 0.21.6 and push the missing tag to the GitHub repo.

If I can make a suggestion for 0.21.7 then I'd like to have #579 cherry picked into that release. It's small fix but it completely blocks using the `lmove` command.

**Comment by djc** [comment]
I think I meant this to be for 0.22 release planning, I just opened #674 for 0.21.7. Would you mind submitting a PR that backports #579 to the 0.21.x branch?

**Comment by djc** [comment]
Pushed the tag, changelog update in #678.

**Comment by jaymell** [comment]
@djc re 0.22.0 / 0.1.0 (redis-test), I'm wondering if we should just plan to tag the crate(s) on latest main once we're confident we have everything we need, or if you see any reason to set the cut-off at an earlier commit. 

I'd like to do some additional testing of the code-base and tend to a few minor clean-up items, but otherwise maybe we can plan to have this out in the next couple weeks?

**Comment by djc** [comment]
I feel like we should at least try to get in-flight PRs like @utkarshgupta137's series in if possible, and maybe review what other public API-changing PRs we have open in the queue.

**Comment by jaymell** [comment]
Closing, since 0.22.0 was released :grin:
