### ISSUE TITLE
0.21.7 release planning

### ISSUE THREAD

**Issue by djc** [redis-rs/redis-rs#674]

**Comment by rudolphfroger-ds** [comment]
I think this can be closed now that 0.22 has been released?

**Comment by jaymell** [comment]
I would like to potentially release a fix for #698 onto 0.21.7, as it is a rather nasty bug that can affect otherwise-correctly formed pipes in certain scenarios.

**Comment by djc** [comment]
@jaymell is #698 a regression or has it been around for a long time? Not sure about our policy of when/how we do maintenance releases.

**Comment by jaymell** [comment]
I'm pretty sure #698 has always been around. I'm not sure what the policy is/should be either, but I feel comfortable creating a release cherry-picking the following changes:
* #699 
* #724 

Both of these issues have potential security implications, and since 0.21.x is still the most widely used version I don't mind doing the work of creating a release here.

**Comment by djc** [comment]
Okay, sounds good!

**Comment by jaymell** [comment]
Fixed by #741
