### ISSUE TITLE
redis/examples/basic.rs:do_atomic_increment_lowlevel and do_atomic_increment why not to use  native "incr"  to demonstrate the atomic increment?

### ISSUE THREAD

**Issue by abelard2008** [redis-rs/redis-rs#681]
When I read the two examples `do_atomic_increment_lowlevel` and `do_atomic_increment`  in `redis/examples/basic.rc`, the comments are `Demonstrates how to do an atomic increment in a very low level way.` and `Demonstrates how to do an atomic increment with transaction support.` 。Do these two comments mean the native command `incr` of Redis cannot guarantee atomicity if I use `redis-rs` ?

PS：Sorry，I don't know whether it is appropriate to write this question here ^_^

**Comment by jaymell** [comment]
The examples are simply to show that incrementing in an otherwise non-atomic way (ie, retrieving a key's value, then manually setting the key to the retrieved value + 1) can be done atomically in the `redis-rs` api, which under the hood is just leveraging redis's built-in mechanisms for doing series of commands atomically. So `incr` away, you'll be fine! :smile:

**Comment by abelard2008** [comment]
Ok，Thanks for @jaymell ‘s explanation
